image:
  - Visual Studio 2022
  
environment:
  CONFIG: Release
  VSVER: 17
  matrix:
    - ARCH: x86
    - ARCH: x64
    #- ARCH: arm64

install:
  - cmake --version
  - git submodule update --init
  # Download PCRE2 sources
  - ps: ./init.ps1 -pcre "10.40"
  # Build and install PCRE2
  - ps: ./build.ps1 -proj pcre2 -config $env:CONFIG -arch $env:ARCH -vsver $env:VSVER -init -install

build_script:
  # Build and install editorconfig-core-c
  - ps: ./build.ps1 -proj core -config $env:CONFIG -arch $env:ARCH -vsver $env:VSVER -init -install

test_script:
  # Run the core tests
  - ps: ./test.ps1 -proj core -config $env:CONFIG -arch $env:ARCH

on_failure:
  - echo. && echo. && echo. && echo "Tests for editorconfig-core-c failed. Here is their detailed output:" && echo. && echo. && echo.
  - cd .\bin\%ARCH%-static\core\Testing\Temporary\
  - type LastTest.log
