.TH "editorconfig_parsing_info" 3 "Tue Nov 22 2011" "EditorConfig" \" -*- nroff -*-
.ad l
.nh
.SH NAME
editorconfig_parsing_info \- 
.PP
A structure that contains the parsing information which should be provided before parsing.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editorconfig/editorconfig.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBconf_file_name\fP"
.br
.ti -1c
.RI "char * \fBerr_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains the parsing information which should be provided before parsing. 
.SH "Field Documentation"
.PP 
.SS "const char* \fBeditorconfig_parsing_info::conf_file_name\fP"The file name of EditorConfig conf file. If this pointer is set to NULL, the file name is set to '.editorconfig' by default. 
.SS "char* \fBeditorconfig_parsing_info::err_file\fP"When a parsing error occured, this will point to a file that caused the parsing error. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EditorConfig from the source code.
