.TH "editorconfig_parsing_out" 3 "Sat Nov 5 2011" "EditorConfig" \" -*- nroff -*-
.ad l
.nh
.SH NAME
editorconfig_parsing_out \- 
.PP
A structure that contains the parsing result.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editorconfig/editorconfig.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBeditorconfig_name_value\fP * \fBname_values\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that contains the parsing result. 
.SH "Field Documentation"
.PP 
.SS "int \fBeditorconfig_parsing_out::count\fP"The total count of name_values structures pointed by name_values pointer 
.SS "struct \fBeditorconfig_name_value\fP* \fBeditorconfig_parsing_out::name_values\fP"Pointer to a list of \fBeditorconfig_name_value\fP structures containing names and values of the parsed result 

.SH "Author"
.PP 
Generated automatically by Doxygen for EditorConfig from the source code.
