.TH "editorconfig_name_value" 3 "Sat Nov 5 2011" "EditorConfig" \" -*- nroff -*-
.ad l
.nh
.SH NAME
editorconfig_name_value \- 
.PP
A structure containing a name and its corresponding value.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editorconfig/editorconfig.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure containing a name and its corresponding value. 
.SH "Field Documentation"
.PP 
.SS "char* \fBeditorconfig_name_value::name\fP"EditorConfig config item's name. 
.SS "char* \fBeditorconfig_name_value::value\fP"EditorConfig config item's value. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EditorConfig from the source code.
